<a href="https://colab.research.google.com/github/KachukwuOkoh/Grip-TSF-DS-ML/blob/master/Copy_of_NumPy_Bootcamp_Graded_Hands_on_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Overview**

Dear Learner, 

Congratulations, you have studied NumPy all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

**Author:** Avantika Podar

###Task 1:   

Construct a random 3x28x28 NumPy array called *original* to represent an image and then convert this into into a 1x(3x28x28) array called *flat*. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.



In [3]:
import numpy as np

In [8]:
original = np.random.randint(10, size=(3,28,28))
original

array([[[5, 5, 0, ..., 7, 8, 4],
        [0, 6, 5, ..., 7, 9, 8],
        [7, 6, 9, ..., 2, 8, 3],
        ...,
        [8, 2, 5, ..., 3, 2, 3],
        [1, 1, 0, ..., 8, 7, 8],
        [7, 1, 5, ..., 8, 6, 7]],

       [[6, 3, 0, ..., 3, 5, 7],
        [0, 9, 4, ..., 7, 3, 7],
        [5, 7, 3, ..., 8, 7, 1],
        ...,
        [5, 1, 1, ..., 4, 1, 3],
        [9, 2, 3, ..., 9, 7, 8],
        [2, 9, 2, ..., 9, 9, 3]],

       [[9, 1, 3, ..., 5, 2, 6],
        [9, 5, 4, ..., 7, 9, 2],
        [4, 5, 7, ..., 9, 1, 7],
        ...,
        [5, 9, 4, ..., 4, 1, 1],
        [9, 3, 2, ..., 9, 4, 5],
        [3, 2, 3, ..., 6, 7, 2]]])

In [10]:
flat = original.flatten()
flat

array([5, 5, 0, ..., 6, 7, 2])

In [12]:
flatten = flat.flatten()
flatten

array([5, 5, 0, ..., 6, 7, 2])

In [13]:
original.shape

(3, 28, 28)

In [14]:
flat.shape

(2352,)

In [15]:
flatten.shape

(2352,)

### Task 2: Print out the following: 
  * dimension of the arrays.
  * memory address of the arrays (pointer).
  * shape of the arrays.
  * data types of the arrays. 




## `Dimension of the arrays`

In [16]:
np.ndim(original)

3

In [18]:
np.ndim(flat)

1

In [20]:
np.ndim(flatten)

1

## `Memory Address of the arrays`

In [21]:
from array import *

In [25]:
origin = array("i",flat)
origin

array('i', [5, 5, 0, 7, 4, 0, 1, 6, 6, 9, 5, 6, 3, 3, 1, 3, 5, 4, 5, 5, 2, 6, 9, 0, 7, 7, 8, 4, 0, 6, 5, 1, 0, 9, 5, 1, 4, 8, 2, 0, 4, 7, 6, 8, 6, 0, 3, 8, 0, 0, 0, 3, 2, 7, 9, 8, 7, 6, 9, 8, 2, 5, 2, 5, 5, 6, 7, 7, 7, 8, 9, 8, 3, 8, 7, 8, 8, 2, 2, 5, 3, 2, 8, 3, 8, 2, 1, 7, 5, 9, 8, 5, 1, 4, 2, 8, 8, 4, 2, 8, 5, 9, 0, 0, 1, 9, 0, 2, 0, 9, 9, 9, 6, 5, 3, 7, 8, 8, 9, 8, 5, 9, 0, 5, 7, 2, 0, 4, 0, 0, 0, 5, 3, 9, 2, 1, 4, 7, 3, 1, 7, 7, 8, 8, 8, 8, 6, 1, 3, 9, 7, 7, 9, 8, 6, 9, 1, 4, 3, 4, 0, 9, 8, 9, 1, 2, 8, 5, 7, 3, 3, 0, 8, 8, 3, 3, 7, 3, 5, 7, 8, 8, 6, 4, 7, 5, 6, 0, 6, 2, 4, 7, 1, 5, 4, 6, 1, 8, 5, 1, 3, 9, 4, 0, 7, 8, 3, 4, 1, 5, 5, 3, 9, 1, 6, 0, 3, 2, 6, 0, 1, 5, 7, 8, 2, 9, 5, 2, 1, 6, 7, 3, 2, 8, 8, 5, 6, 0, 4, 4, 8, 5, 0, 2, 0, 9, 9, 3, 3, 2, 1, 9, 2, 3, 5, 5, 9, 8, 6, 4, 9, 0, 3, 1, 8, 1, 4, 4, 2, 9, 0, 2, 4, 1, 3, 6, 2, 4, 6, 0, 7, 4, 9, 1, 1, 5, 7, 6, 6, 2, 1, 0, 1, 3, 6, 3, 6, 6, 9, 4, 0, 3, 8, 0, 4, 3, 8, 1, 7, 8, 1, 6, 9, 9, 7, 6, 4, 0, 6, 1, 5, 6, 1, 5, 8, 4, 3, 2, 0, 8

In [28]:
print("Current memory address and the length in elements of the buffer: "+str(origin.buffer_info()))
print("The size of the memory buffer in bytes: "+str(origin.buffer_info()[1] * origin.itemsize)) 

Current memory address and the length in elements of the buffer: (94189692182528, 2352)
The size of the memory buffer in bytes: 9408


## `Shape of the arrays`

In [59]:
original.shape

(3, 28, 28)

In [60]:
flat.shape

(2352,)

In [61]:
flatten.shape

(2352,)

## `Datatypes of the arrays`

In [63]:
type(original)

numpy.ndarray

In [64]:
type(flat)

numpy.ndarray

In [65]:
type(flatten)

numpy.ndarray

### Task 3: 
Construct a new array which is a negative of the *original* array, i.e, all elements are negative of those in the *original* array. Print the new array. Add the original and new arrays. Print the result. 

In [55]:
fake = np.negative(original)
fake

array([[[-5, -5,  0, ..., -7, -8, -4],
        [ 0, -6, -5, ..., -7, -9, -8],
        [-7, -6, -9, ..., -2, -8, -3],
        ...,
        [-8, -2, -5, ..., -3, -2, -3],
        [-1, -1,  0, ..., -8, -7, -8],
        [-7, -1, -5, ..., -8, -6, -7]],

       [[-6, -3,  0, ..., -3, -5, -7],
        [ 0, -9, -4, ..., -7, -3, -7],
        [-5, -7, -3, ..., -8, -7, -1],
        ...,
        [-5, -1, -1, ..., -4, -1, -3],
        [-9, -2, -3, ..., -9, -7, -8],
        [-2, -9, -2, ..., -9, -9, -3]],

       [[-9, -1, -3, ..., -5, -2, -6],
        [-9, -5, -4, ..., -7, -9, -2],
        [-4, -5, -7, ..., -9, -1, -7],
        ...,
        [-5, -9, -4, ..., -4, -1, -1],
        [-9, -3, -2, ..., -9, -4, -5],
        [-3, -2, -3, ..., -6, -7, -2]]])

In [57]:
neutral = original + fake
neutral

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]])

###Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [29]:
print (original[1,1,0:11])

[0 9 4 2 7 4 0 6 3 7 4]


### Task 5 
A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

## `Using the 'original' variable as our image color channels`

In [30]:
print (original[2,0:3,:].shape)

(3, 28)


In [31]:
print (original[2,:,:].shape)

(28, 28)


In [32]:
print (original[2,0:3,:])

[[9 1 3 6 6 3 4 0 7 1 9 7 7 9 7 2 5 8 5 2 9 4 0 8 0 5 2 6]
 [9 5 4 4 5 4 6 5 2 5 3 9 8 3 0 3 2 7 8 6 6 0 5 4 9 7 9 2]
 [4 5 7 0 8 5 4 4 8 5 8 2 7 8 6 3 4 4 6 9 4 0 7 0 5 9 1 7]]


### Task 6 
Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose. 

In [35]:
lst = []
for i in range(2,101):
    if i%2==0:
        lst.append(i)
even = np.array(lst)
even

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [43]:
even_convert = even.reshape((10,5))
even_convert
#print (even_convert.size)

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [39]:
even_convert.transpose()

array([[  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

###Task 7 
Consider the 10x5 array created in Task 6. Find the mean each row and column. You may use in built functions or write your own code.

In [54]:
rows = np.mean(even_convert, 1)
print ('Mean for each row', rows)
print ()
columns = np.mean(even_convert, 0)
print ('Mean for each column', columns)


Mean for each row [ 6. 16. 26. 36. 46. 56. 66. 76. 86. 96.]

Mean for each column [47. 49. 51. 53. 55.]


### Task 8
Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

## `Answer`

We can not create a 3x3 array for the first 50 even numbers because the size of the created array should equal 50 and 3x3 equals 9 hence impossible.

However, values of mxn dimensions allowed are:
1x50, 2x25, 5x10, 10x5, 25x2, 50x1